- name: pass the vars from outsides
  hosts: localhost
  vars_files:
    vars.yaml
  tasks:
  - name: print the var files
    ansible.builtin.debug:
      msg: "my company is {{company}} and manager name is {[manager]} and area is {{area}}"