- name: print the inventory vars
  hosts: localhost
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "my company is {{company}} and manager is {{manager}} and area is {{area}}"