- name: check user is there or not with conditions
  hosts: web
  become: yes
  tasks:
    - name: check user is there or not
      ansible.builtin.command: id expense
      register: user
      ignore_errors: true
    
    - name: print the user information
      ansible.builtin.debug:
        msg: "user info is {{user}}"

    - name: print the conditions
      ansible.builtin.command: useradd expense
      when: user.rc != 0



    - name: print the information
      ansible.builtin.debug:
        msg: "this is conditions"
    