- name: check user is there or not with conditions
  hosts: web
  tasks:
    - name: check user is there or not
      ansible.builtin.command: id expense

    - name: print the information
      ansible.builtin.debug:
        msg: "this is conditions"
